import { Shipment } from "@/lib/types";

export const initialMockShipments: Shipment[] = [
  {
    id: "SHP-001",
    trackingNumber: "TRK-9821-DAIRY",
    farmerId: "usr_farm_elena",
    transporterId: "usr_trans_marcus",
    warehouseId: "usr_wh_sarah",
    retailerId: "usr_ret_david",
    produce: {
      id: "PRD-01",
      name: "Pasteurized Whole Milk",
      category: "Dairy",
      quantityKg: 2400,
      optimalTempMin: 1.5,
      optimalTempMax: 4.0,
      optimalHumidityMin: 65,
      optimalHumidityMax: 85,
    },
    origin: {
      name: "Green Valley Farm Hub",
      address: "128 Meadow Way, Salinas CA",
      coordinates: { lat: 36.6777, lng: -121.6555 },
      reachedAt: "2026-09-28T06:00:00Z",
    },
    destination: {
      name: "Metro Cold Depot #4",
      address: "890 Industrial Blvd, San Jose CA",
      coordinates: { lat: 37.3382, lng: -121.8863 },
    },
    status: "InTransit",
    currentLocation: { lat: 37.05, lng: -121.72 },
    temperatureAlert: false,
    humidityAlert: false,
    tamperAlert: false,
    createdAt: "2026-09-28T06:00:00Z",
    dispatchedAt: "2026-09-28T07:30:00Z",
    updatedAt: "2026-09-28T10:30:00Z",
  },
  {
    id: "SHP-002",
    trackingNumber: "TRK-9822-BERRY",
    farmerId: "usr_farm_elena",
    transporterId: "usr_trans_marcus",
    warehouseId: "usr_wh_sarah",
    produce: {
      id: "PRD-02",
      name: "Organic Strawberries",
      category: "Fruits",
      quantityKg: 1200,
      optimalTempMin: 0.5,
      optimalTempMax: 2.0,
      optimalHumidityMin: 90,
      optimalHumidityMax: 95,
    },
    origin: {
      name: "Sunny Ridge Berry Farm",
      address: "44 Berry Lane, Watsonville CA",
      coordinates: { lat: 36.9102, lng: -121.7558 },
    },
    destination: {
      name: "Pacific Distribution Hub",
      address: "500 Logistics Way, Oakland CA",
      coordinates: { lat: 37.8044, lng: -122.2712 },
    },
    status: "Harvested",
    temperatureAlert: false,
    humidityAlert: false,
    tamperAlert: false,
    createdAt: "2026-09-28T07:15:00Z",
    updatedAt: "2026-09-28T07:15:00Z",
  },
  {
    id: "SHP-003",
    trackingNumber: "TRK-9823-SALMON",
    farmerId: "usr_farm_elena",
    transporterId: "usr_trans_marcus",
    warehouseId: "usr_wh_sarah",
    retailerId: "usr_ret_david",
    produce: {
      id: "PRD-03",
      name: "King Salmon Fillets",
      category: "Seafood",
      quantityKg: 850,
      optimalTempMin: -1.0,
      optimalTempMax: 1.5,
      optimalHumidityMin: 85,
      optimalHumidityMax: 95,
    },
    origin: {
      name: "Bodega Bay Fisheries",
      address: "12 Harbor Way, Bodega Bay CA",
      coordinates: { lat: 38.3333, lng: -123.0481 },
    },
    destination: {
      name: "Metro Cold Storage",
      address: "1400 3rd St, San Francisco CA",
      coordinates: { lat: 37.7749, lng: -122.4194 },
    },
    status: "ColdStorage",
    currentLocation: { lat: 37.7749, lng: -122.4194 },
    temperatureAlert: false,
    humidityAlert: false,
    tamperAlert: false,
    createdAt: "2026-09-27T18:00:00Z",
    updatedAt: "2026-09-28T05:00:00Z",
  },
  {
    id: "SHP-004",
    trackingNumber: "TRK-9824-BEEF",
    farmerId: "usr_farm_elena",
    transporterId: "usr_trans_marcus",
    retailerId: "usr_ret_david",
    produce: {
      id: "PRD-04",
      name: "Angus Beef Cuts",
      category: "Meat",
      quantityKg: 3100,
      optimalTempMin: -2.0,
      optimalTempMax: 0.0,
      optimalHumidityMin: 75,
      optimalHumidityMax: 85,
    },
    origin: {
      name: "Highland Ranch Cattle",
      address: "700 Meadow Grass, Paso Robles CA",
      coordinates: { lat: 35.6369, lng: -120.6545 },
    },
    destination: {
      name: "Pacific Organic Market",
      address: "2100 California Ave, Palo Alto CA",
      coordinates: { lat: 37.4419, lng: -122.143 },
    },
    status: "Delivered",
    temperatureAlert: false,
    humidityAlert: false,
    tamperAlert: false,
    createdAt: "2026-09-26T10:00:00Z",
    deliveredAt: "2026-09-27T16:30:00Z",
    updatedAt: "2026-09-27T16:30:00Z",
  },
  {
    id: "SHP-005",
    trackingNumber: "TRK-9825-AVOCADO",
    farmerId: "usr_farm_elena",
    produce: {
      id: "PRD-05",
      name: "Hass Avocados Grade-A",
      category: "Fruits",
      quantityKg: 4200,
      optimalTempMin: 4.5,
      optimalTempMax: 7.0,
      optimalHumidityMin: 80,
      optimalHumidityMax: 90,
    },
    origin: {
      name: "Carpinteria Orchards",
      address: "310 Casitas Pass, Carpinteria CA",
      coordinates: { lat: 34.3989, lng: -119.5185 },
    },
    destination: {
      name: "Northwest Food Depot",
      address: "1900 Airport Way, Seattle WA",
      coordinates: { lat: 47.6062, lng: -122.3321 },
    },
    status: "Draft",
    temperatureAlert: false,
    humidityAlert: false,
    tamperAlert: false,
    createdAt: "2026-09-28T09:00:00Z",
    updatedAt: "2026-09-28T09:00:00Z",
  },
  {
    id: "SHP-006",
    trackingNumber: "TRK-9826-TULIPS",
    farmerId: "usr_farm_elena",
    transporterId: "usr_trans_marcus",
    warehouseId: "usr_wh_sarah",
    produce: {
      id: "PRD-06",
      name: "Cut Premium Tulips",
      category: "Flowers",
      quantityKg: 620,
      optimalTempMin: 1.0,
      optimalTempMax: 3.0,
      optimalHumidityMin: 85,
      optimalHumidityMax: 95,
    },
    origin: {
      name: "Skagit Floral Nursery",
      address: "155 Best Rd, Mount Vernon WA",
      coordinates: { lat: 48.4212, lng: -122.334 },
    },
    destination: {
      name: "Flower Terminal Depot",
      address: "640 Brannan St, San Francisco CA",
      coordinates: { lat: 37.7785, lng: -122.3995 },
    },
    status: "Compromised",
    temperatureAlert: true,
    humidityAlert: false,
    tamperAlert: false,
    createdAt: "2026-09-27T04:00:00Z",
    dispatchedAt: "2026-09-27T08:00:00Z",
    updatedAt: "2026-09-28T02:00:00Z",
  },
  {
    id: "SHP-007",
    trackingNumber: "TRK-9827-CHEESE",
    farmerId: "usr_farm_elena",
    transporterId: "usr_trans_marcus",
    retailerId: "usr_ret_david",
    produce: {
      id: "PRD-07",
      name: "Artisan Aged Cheddar",
      category: "Dairy",
      quantityKg: 1500,
      optimalTempMin: 2.0,
      optimalTempMax: 5.0,
      optimalHumidityMin: 70,
      optimalHumidityMax: 80,
    },
    origin: {
      name: "Point Reyes Farmstead",
      address: "14700 CA-1, Point Reyes CA",
      coordinates: { lat: 38.0691, lng: -122.8069 },
    },
    destination: {
      name: "Sacramento Distribution Hub",
      address: "400 R St, Sacramento CA",
      coordinates: { lat: 38.5816, lng: -121.4944 },
    },
    status: "InTransit",
    currentLocation: { lat: 38.25, lng: -122.1 },
    temperatureAlert: false,
    humidityAlert: false,
    tamperAlert: false,
    createdAt: "2026-09-28T04:30:00Z",
    dispatchedAt: "2026-09-28T06:00:00Z",
    updatedAt: "2026-09-28T08:15:00Z",
  },
  {
    id: "SHP-008",
    trackingNumber: "TRK-9828-SPINACH",
    farmerId: "usr_farm_elena",
    produce: {
      id: "PRD-08",
      name: "Organic Baby Spinach",
      category: "Vegetables",
      quantityKg: 950,
      optimalTempMin: 0.5,
      optimalTempMax: 2.5,
      optimalHumidityMin: 95,
      optimalHumidityMax: 98,
    },
    origin: {
      name: "Salinas Valley Farm Hub",
      address: "900 Alisal Rd, Salinas CA",
      coordinates: { lat: 36.65, lng: -121.62 },
    },
    destination: {
      name: "East Bay Fresh Warehouse",
      address: "41000 Warm Springs Blvd, Fremont CA",
      coordinates: { lat: 37.51, lng: -121.93 },
    },
    status: "Harvested",
    temperatureAlert: false,
    humidityAlert: false,
    tamperAlert: false,
    createdAt: "2026-09-28T08:00:00Z",
    updatedAt: "2026-09-28T08:00:00Z",
  },

];
