import { Shipment } from "@/lib/types";

export const initialMockShipments: Shipment[] = [
  {
    id: "SHP-001",
    trackingNumber: "TRK-9821-DAIRY",
    farmerId: "usr_farm_elena",
    transporterId: "usr_trans_marcus",
    warehouseId: "usr_wh_sarah",
    retailerId: "usr_ret_david",
    produce: {
      id: "PRD-01",
      name: "Fresh Buffalo Milk",
      category: "Dairy",
      quantityKg: 2400,
      optimalTempMin: 1.5,
      optimalTempMax: 4.0,
      optimalHumidityMin: 65,
      optimalHumidityMax: 85,
    },
    origin: {
      name: "Sargodha Dairy Cooperative",
      address: "University Road, Sargodha",
      coordinates: { lat: 32.0836, lng: 72.6711 },
      reachedAt: "2026-09-28T06:00:00Z",
    },
    destination: {
      name: "Lahore Cold Storage",
      address: "Kot Lakhpat Industrial Estate, Lahore",
      coordinates: { lat: 31.5204, lng: 74.3587 },
    },
    status: "InTransit",
    currentLocation: { lat: 31.5206, lng: 74.3586 },
    temperatureAlert: false,
    humidityAlert: false,
    tamperAlert: false,
    createdAt: "2026-09-28T06:00:00Z",
    dispatchedAt: "2026-09-28T07:30:00Z",
    updatedAt: "2026-09-28T10:30:00Z",
  },
  {
    id: "SHP-002",
    trackingNumber: "TRK-9822-BERRY",
    farmerId: "usr_farm_elena",
    transporterId: "usr_trans_marcus",
    warehouseId: "usr_wh_sarah",
    produce: {
      id: "PRD-02",
      name: "Organic Guava",
      category: "Fruits",
      quantityKg: 1200,
      optimalTempMin: 0.5,
      optimalTempMax: 2.0,
      optimalHumidityMin: 90,
      optimalHumidityMax: 95,
    },
    origin: {
      name: "Multan Guava Orchard",
      address: "Shujabad Road, Multan",
      coordinates: { lat: 30.1575, lng: 71.5249 },
    },
    destination: {
      name: "Faisalabad Logistics Hub",
      address: "Jaranwala Road, Faisalabad",
      coordinates: { lat: 31.4504, lng: 73.135 },
    },
    status: "Harvested",
    temperatureAlert: false,
    humidityAlert: false,
    tamperAlert: false,
    createdAt: "2026-09-28T07:15:00Z",
    updatedAt: "2026-09-28T07:15:00Z",
  },
  {
    id: "SHP-003",
    trackingNumber: "TRK-9823-SALMON",
    farmerId: "usr_farm_elena",
    transporterId: "usr_trans_marcus",
    warehouseId: "usr_wh_sarah",
    retailerId: "usr_ret_david",
    produce: {
      id: "PRD-03",
      name: "Indus River Fish Fillets",
      category: "Seafood",
      quantityKg: 850,
      optimalTempMin: -1.0,
      optimalTempMax: 1.5,
      optimalHumidityMin: 85,
      optimalHumidityMax: 95,
    },
    origin: {
      name: "Sukkur Fisheries Cooperative",
      address: "Barrage Road, Sukkur",
      coordinates: { lat: 27.7244, lng: 68.8228 },
    },
    destination: {
      name: "Karachi Cold Storage",
      address: "Korangi Industrial Area, Karachi",
      coordinates: { lat: 24.8607, lng: 67.0011 },
    },
    status: "ColdStorage",
    currentLocation: { lat: 24.8607, lng: 67.0011 },
    temperatureAlert: false,
    humidityAlert: false,
    tamperAlert: false,
    createdAt: "2026-09-27T18:00:00Z",
    updatedAt: "2026-09-28T05:00:00Z",
  },
  {
    id: "SHP-004",
    trackingNumber: "TRK-9824-BEEF",
    farmerId: "usr_farm_elena",
    transporterId: "usr_trans_marcus",
    retailerId: "usr_ret_david",
    produce: {
      id: "PRD-04",
      name: "Chilled Beef Cuts",
      category: "Meat",
      quantityKg: 3100,
      optimalTempMin: -2.0,
      optimalTempMax: 0.0,
      optimalHumidityMin: 75,
      optimalHumidityMax: 85,
    },
    origin: {
      name: "Bahawalpur Livestock Farm",
      address: "Ahmedpur Road, Bahawalpur",
      coordinates: { lat: 29.3956, lng: 71.6836 },
    },
    destination: {
      name: "Lahore Produce Market",
      address: "Badami Bagh, Lahore",
      coordinates: { lat: 31.5204, lng: 74.3587 },
    },
    status: "Delivered",
    temperatureAlert: false,
    humidityAlert: false,
    tamperAlert: false,
    createdAt: "2026-09-26T10:00:00Z",
    deliveredAt: "2026-09-27T16:30:00Z",
    updatedAt: "2026-09-27T16:30:00Z",
  },
  {
    id: "SHP-005",
    trackingNumber: "TRK-9825-AVOCADO",
    farmerId: "usr_farm_elena",
    produce: {
      id: "PRD-05",
      name: "Sindh Mangoes Grade-A",
      category: "Fruits",
      quantityKg: 4200,
      optimalTempMin: 4.5,
      optimalTempMax: 7.0,
      optimalHumidityMin: 80,
      optimalHumidityMax: 90,
    },
    origin: {
      name: "Mirpur Khas Mango Farm",
      address: "Sindhri Road, Mirpur Khas",
      coordinates: { lat: 25.5276, lng: 69.0126 },
    },
    destination: {
      name: "Gujranwala Food Depot",
      address: "GT Road, Gujranwala",
      coordinates: { lat: 32.1877, lng: 74.1945 },
    },
    status: "Draft",
    temperatureAlert: false,
    humidityAlert: false,
    tamperAlert: false,
    createdAt: "2026-09-28T09:00:00Z",
    updatedAt: "2026-09-28T09:00:00Z",
  },
  {
    id: "SHP-006",
    trackingNumber: "TRK-9826-TULIPS",
    farmerId: "usr_farm_elena",
    transporterId: "usr_trans_marcus",
    warehouseId: "usr_wh_sarah",
    produce: {
      id: "PRD-06",
      name: "Fresh Jasmine Flowers",
      category: "Flowers",
      quantityKg: 620,
      optimalTempMin: 1.0,
      optimalTempMax: 3.0,
      optimalHumidityMin: 85,
      optimalHumidityMax: 95,
    },
    origin: {
      name: "Pattoki Flower Nursery",
      address: "Multan Road, Pattoki",
      coordinates: { lat: 31.0209, lng: 73.8478 },
    },
    destination: {
      name: "Islamabad Flower Terminal",
      address: "I-9 Industrial Area, Islamabad",
      coordinates: { lat: 33.6844, lng: 73.0479 },
    },
    status: "Compromised",
    temperatureAlert: true,
    humidityAlert: false,
    tamperAlert: false,
    createdAt: "2026-09-27T04:00:00Z",
    dispatchedAt: "2026-09-27T08:00:00Z",
    updatedAt: "2026-09-28T02:00:00Z",
  },
  {
    id: "SHP-007",
    trackingNumber: "TRK-9827-CHEESE",
    farmerId: "usr_farm_elena",
    transporterId: "usr_trans_marcus",
    retailerId: "usr_ret_david",
    produce: {
      id: "PRD-07",
      name: "Artisan Aged Cheddar",
      category: "Dairy",
      quantityKg: 1500,
      optimalTempMin: 2.0,
      optimalTempMax: 5.0,
      optimalHumidityMin: 70,
      optimalHumidityMax: 80,
    },
    origin: {
      name: "Okara Dairy Farm",
      address: "Depalpur Road, Okara",
      coordinates: { lat: 30.8081, lng: 73.4458 },
    },
    destination: {
      name: "Multan Distribution Hub",
      address: "Vehari Road, Multan",
      coordinates: { lat: 30.1575, lng: 71.5249 },
    },
    status: "InTransit",
    currentLocation: { lat: 30.72, lng: 72.42 },
    temperatureAlert: false,
    humidityAlert: false,
    tamperAlert: false,
    createdAt: "2026-09-28T04:30:00Z",
    dispatchedAt: "2026-09-28T06:00:00Z",
    updatedAt: "2026-09-28T08:15:00Z",
  },
  {
    id: "SHP-008",
    trackingNumber: "TRK-9828-SPINACH",
    farmerId: "usr_farm_elena",
    produce: {
      id: "PRD-08",
      name: "Organic Spinach",
      category: "Vegetables",
      quantityKg: 950,
      optimalTempMin: 0.5,
      optimalTempMax: 2.5,
      optimalHumidityMin: 95,
      optimalHumidityMax: 98,
    },
    origin: {
      name: "Quetta Valley Farm Hub",
      address: "Sariab Road, Quetta",
      coordinates: { lat: 30.1798, lng: 66.975 },
    },
    destination: {
      name: "Islamabad Fresh Warehouse",
      address: "I-10 Industrial Area, Islamabad",
      coordinates: { lat: 33.6844, lng: 73.0479 },
    },
    status: "Harvested",
    temperatureAlert: false,
    humidityAlert: false,
    tamperAlert: false,
    createdAt: "2026-09-28T08:00:00Z",
    updatedAt: "2026-09-28T08:00:00Z",
  },

];
